### ISSUE TITLE
cannot import harmonic_conv

### ISSUE THREAD

**Issue by mayfool** [taketakeseijin/HarmonicLowering#1]
when I  "import harmonic_conv", get the default like this:
/usr/local/anaconda3/envs/torchxx/lib/python3.6/site-packages/interp_same-0.0.0-py3.6-linux-x86_64.egg/interp_same.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

**Comment by taketakeseijin** [comment]
This is a [bug](https://github.com/pytorch/pytorch/issues/38122) of c++ extension for pytorch >=1.5.
There're 2 ways to avoid this error.
1. Use pytorch < 1.5
2. Export an environmental variable like below
```sh
export TORCH_USE_RTLD_GLOBAL=YES
# python -c "import harmonic_conv" # this don't throw the error
```

**Comment by mayfool** [comment]
I reinstall the torch==1.3 and export the environmental variable as you said.However, it still doesn't work, i get the same error as before.

**Comment by mayfool** [comment]
> I reinstall the torch==1.3 and export the environmental variable as you said.However, it still doesn't work, i get the same error as before.

Sorry,I didn't delete history build/ dir.Now, it works.Thank you for reply.
