### ISSUE TITLE
RuntimeError: expected scalar type Int but found Float

### ISSUE THREAD

**Issue by eloimoliner** [taketakeseijin/HarmonicLowering#2]
Hello! 
Thanks for this useful repository :) 

I tried to run it but I found this error. I'm using pytorch 1.9.0 and CUDA 11.4

>   File "/scratch/work/molinee2/unet_dir/bwe_pytorch/harmonic_conv.py", line 68, in forward
>     lowered_input = self.HL(input)
>   File "/scratch/work/molinee2/conda_envs/torch_denoiser/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/scratch/work/molinee2/unet_dir/bwe_pytorch/Lowering.py", line 66, in forward
>     lowered_input[:,self.channel_slice_func(fk)] = self.parallelized(input,k=fk+1)
>   File "/scratch/work/molinee2/unet_dir/bwe_pytorch/Lowering.py", line 91, in parallelized
>     return self.zoom(input,k,self.anchor)
>   File "/scratch/work/molinee2/conda_envs/torch_denoiser/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/scratch/work/molinee2/unet_dir/bwe_pytorch/interp_function.py", line 97, in forward
>     return ZoomFunctional(input, k, n)
>   File "/scratch/work/molinee2/unet_dir/bwe_pytorch/interp_function.py", line 59, in forward
>     IS.interp_affine(inputs,output,indexes,weights,k,n)
> RuntimeError: expected scalar type Int but found Float

It seems like the "indexes" variable in the following line is a float tensor, while it should be integer:
https://github.com/taketakeseijin/HarmonicLowering/blob/b444371a3806aee1cf0dad1a4371a98f678cdd9b/src/interp_function.py#L58

In case someone else gets this error, it seems to be easily solved by adding:
`indexes=indexes.int()`

**Comment by fmiotello** [comment]
@eloimoliner did you manage to solve this problem? I get the same error, also when adding `indexes=indexes.int()`.

**Comment by eloimoliner** [comment]
make sure you do it everywhere IS.interp_affine is called. I think it is twice throghout the code.

**Comment by taketakeseijin** [comment]
I recommend insert below line after [this line.](https://github.com/taketakeseijin/HarmonicLowering/blob/master/src/interp_function.py#L47)
```py
index=index.int()
```
