### ISSUE TITLE
import module on another terminal

### ISSUE THREAD

**Issue by mayfool** [taketakeseijin/HarmonicLowering#3]
After I install the module on the terminal, I can import harmonic_conv.However, when I open another terminal, and try to import the module, it tells me "No module named ‘harmonic_conv'".

**Comment by taketakeseijin** [comment]
Be sure to import harmonic_conv after importing torch.

OK
```py
import torch
import harmonic_conv
```

NG (may throw an error)
```py
import harmonic_conv
```

Ref: [Official Introduction](https://pytorch.org/tutorials/advanced/cpp_extension.html#using-your-extension)

**Comment by mayfool** [comment]
It'ok when torch==1.4.0,while get the same error when torch==1.3.0.Thanks, i can use it now.
